### ISSUE TITLE
[Bug]: first_valid_line ValueError: True not in list

### ISSUE THREAD

**Issue by otirmizi** [opera-adt/s1-reader#43]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

```
Traceback (most recent call last):
  File "/DataFS/otirmizi/JPL/asc_stack/s1_geo_stack.py", line 507, in <module>
    main(args.slc_dir, args.dem_file, args.burst_id, args.ref_date,
  File "/DataFS/otirmizi/JPL/asc_stack/s1_geo_stack.py", line 484, in main
    bursts = load_bursts(safe, orbit_path, subswath)
  File "/home/users/otirmizi/tools/s1-reader/src/s1reader/s1_reader.py", line 476, in load_bursts
    bursts = _burst_from_zip(path, id_str, orbit_path)
  File "/home/users/otirmizi/tools/s1-reader/src/s1reader/s1_reader.py", line 537, in _burst_from_zip
    bursts = burst_from_xml(f_annotation, orbit_path, f_tiff, iw2_f_annotation, z_file.open)
  File "/home/users/otirmizi/tools/s1-reader/src/s1reader/s1_reader.py", line 380, in burst_from_xml
    first_valid_line = [x > 0 for x in first_valid_samples].index(True)
ValueError: True is not in list
```

This seems to be an issue arising from a handful of safe files, with the majority of them being 2016 and 2017 acquisitions for S1A

### What did you expect?

I expected [...]

### Reproducible steps

```bash
some of the zip_files =   S1A_IW_SLC__1SSV_20160829T230628_20160829T230655_012821_014394_A1F0.zip
                          S1A_IW_SLC__1SDV_20170101T002609_20170101T002639_014631_017CA0_1FAB.zip
                          S1A_IW_SLC__1SDV_20170101T002637_20170101T002705_014631_017CA0_5292.zip
                          S1A_IW_SLC__1SDV_20170113T002609_20170113T002639_014806_0181ED_ADE5.zip
                          S1A_IW_SLC__1SDV_20170125T002609_20170125T002638_014981_01875E_8F78.zip
                          S1A_IW_SLC__1SDV_20181222T002623_20181222T002653_025131_02C66C_FF54.zip
                          S1B_IW_SLC__1SDV_20190614T002608_20190614T002638_016685_01F668_3EF4.zip
                          S1B_IW_SLC__1SDV_20190626T002611_20190626T002641_016860_01FB95_3A63.zip

orbit_dir = './orbits'
orbit_path = s1reader.get_orbit_file_from_dir(zip_path, orbit_dir)
bursts = s1reader.load_bursts(zip_path, orbit_path, swath_num=2)
```

### Environment

```bash
- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...
```

**Comment by yunjunz** [comment]
My testing confirms the same error for all the zip files above, except for the one at 2016-08-29.
